version: '2'
services:
  application:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/src
    command: init migrate bash
    environment:
      - POSTGRES_DATABASE=twitter_mentions_dev
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=postgres
  postgres:
    ports:
      - "15432:5432"
    image: postgres:9.6
    environment:
      - POSTGRES_DB=twitter_mentions_dev
    command: "-c max_connections=256"